[package]
name = "penrose-sminez"
version = "0.1.0"
authors = ["IDAM <innes.andersonmorrison@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "penrose"
path = "src/wm/main.rs"

[[bin]]
doc = false
name = "pmenu"
path = "src/pmenu/main.rs"

[dependencies]
fuzzy-matcher = "0.3.7"
log = "0.4.8"
penrose = { path = "/home/innes/repos/personal/penrose", features = [ "xcb", "xcb_draw", "xcb_keysyms" ] }
simplelog = "0.8.0"
