[package]
name = "penrose-sminez"
version = "0.1.0"
authors = ["IDAM <innes.andersonmorrison@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "penrose"
path = "src/main.rs"

[dependencies]
log = "0.4.8"
penrose = { git = "https://github.com/sminez/penrose", branch = "develop" }
simplelog = "0.8.0"
